spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: postgres
    password: admin1234

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true

server:
  port: 8080


jwt:
  secret: your-super-secret-key-for-development
  expiration: 900000